version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt-github-integration
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SERVER_DOMAIN=${SERVER_DOMAIN:-your-server-domain.com}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN:-https://chat.openai.com}
      - ENABLE_SSL=${ENABLE_SSL:-false}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-"RedisSecurePassword!"}
    volumes:
      - ./data/logs:/opt/chatgpt-github-integration/logs
      - ./data/cache:/opt/chatgpt-github-integration/cache
      - letsencrypt:/etc/letsencrypt
    networks:
      - chatgpt-github-net
    # Security enhancements
    security_opt:
      - no-new-privileges:true
    read_only: false  # Can't be fully read-only due to Redis, but we limit writable paths
    tmpfs:
      - /tmp
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  chatgpt-github-net:
    driver: bridge

volumes:
  letsencrypt:
    driver: local

# Uncomment the below section to use Docker secrets instead of environment variables
# secrets:
#   github_client_id:
#     file: ./secrets/github_client_id.txt
#   github_client_secret:
#     file: ./secrets/github_client_secret.txt
#   session_secret:
#     file: ./secrets/session_secret.txt
#   redis_password:
#     file: ./secrets/redis_password.txt
